---
- include_tasks: system.yml

- name: Remove packages
  apt: 
    pkg: "{{ remove_packages }}"
    state: absent
    autoremove: yes
    purge: yes

- include_tasks: timedatectl.yml
  when: timedatectl_enabled == true

- name: Install basic packages
  apt: 
    pkg: "{{ base_packages + packages }}"
    state: present
    update_cache: yes
    force: yes

- name: Configure motd 
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: motd.j2, dest: "{{ motd }}" }

- include_tasks: users.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: "user_item"
  when: users is defined

- name: zsh for root user
  file:
    path: "{{ root_home }}/.zshrc"
    state: touch
  become: yes
  when: zsh_shared == true

- name: Include zsh config for root
  lineinfile:
    path: "{{ root_home  }}/.zshrc"
    line: "source /usr/share/zsh-config/.zshrc"
  when: zsh_shared == true

- name: install python modules
  pip:
    name:  "{{ pip_packages | join(' ')}}"
    state: present
