---

### Install basic system packages
- name: Install basic packages
  apt: 
    pkg: "{{ packages + base_packages }}"
    state: present

### Convenience
- name: Configure inputrc | gitconfig | motd 
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: inputrc.j2, dest: "{{ root_inputrc }}" }
   - { src: inputrc.j2, dest: "{{ user_inputrc }}" }
   - { src: motd.j2, dest: "{{ motd }}" }
   - { src: gitconfig.j2, dest: "{{ user_gitconfig }}" }
   - { src: gitignore_global.j2, dest: "{{ user_gitignore_global }}" }

- name: Others System tricks
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/sysctl.conf', line: "vm.overcommit_memory={{ over_commit_memory }}" }
    - { path: '/etc/systemd/journald.conf', line: "SystemMaxUse={{ system_max_use }}" }
