---

### Install basic system packages
- name: Install basic packages
  apt: 
    pkg: "{{ packages + base_packages }}"
    state: present

### Convenience
- name: Configure motd 
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: motd.j2, dest: "{{ motd }}" }

- name: System tricks
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/sysctl.conf', line: "vm.overcommit_memory={{ over_commit_memory }}" }
    - { path: '/etc/systemd/journald.conf', line: "SystemMaxUse={{ system_max_use }}" }

# adding more infos to users after role-users
- include_tasks: users.yml
  loop: "{{ users }}"
  when: users is defined