---
- name: System tricks
  become: yes
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/sysctl.conf', line: "vm.overcommit_memory={{ over_commit_memory }}" }
    - { path: '/etc/systemd/journald.conf', line: "SystemMaxUse={{ system_max_use }}" }

- name: Kernel panic disable
  sysctl:
    name: kernel.panic
    state: absent
    sysctl_file: /etc/sysctl.conf

- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^UseDNS'
      line: 'UseDNS no'
    - regexp: '^GSSAPIAuthentication'
      line: 'GSSAPIAuthentication no'

- name: Configure SSH users ACL
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "AllowUsers {{ item.user }}@{{ item.ippattern }}"
    state: present
  with_items: "{{ ssh_acl_ip|d(false) }}"

- name: 'Clock : Setup timesync config'
  template:
    src: timedatectl.conf.j2
    dest: /etc/systemd/timesyncd.conf
  notify: restart timesyncd
  when: ansible_service_mgr == "systemd" and timedatectl_enabled == true


- name: enable ntp
  command: timedatectl set-ntp true
  notify: restart timesyncd

- name: set Timezone
  timezone:
    name: "{{ timedatectl_timezone }}"
  when: ansible_service_mgr == "systemd" and timedatectl_enabled == true
  notify: restart timesyncd

- name: install keyboard-configuration
  become: yes
  apt:
    name: keyboard-configuration
    state: present
  when: ansible_os_family == 'Debian'

- name: write keyboard configration
  become: yes
  template:
    src: keyboards.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: New keyboard configuration persist
  become: yes
  command: dpkg-reconfigure keyboard-configuration
  ignore_errors: yes #TOFIX

- name: Remove packages
  package:
    name: "{{ remove_packages }}"
    state: absent
    autoremove: yes
    purge: yes

- name: Install basic packages
  package:
    name: "{{ base_packages + packages }}"
    state: present
    update_cache: yes
    force: yes
  become: yes

- name: install python modules
  pip:
    name:  "{{ pip_packages }}"
    state: present
  become: yes
  become_user: root

- name: Configure motd
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: motd.j2, dest: "{{ motd }}" }
