---

- name: Setup timesync config
  template:
    src: timedatectl.conf.j2
    dest: /etc/systemd/timesyncd.conf
  notify: run Timedatectl
  when: ansible_service_mgr == "systemd"

- name: set Timezone
  timezone: 
    name: "{{ timedatectl_timezone }}"
  when: ansible_service_mgr == "systemd"

- name: Make sure timesync is enabled
  systemd:
    state: started
    name: systemd-timesyncd
