---

# get user on github
- name: Ensure authorized_keys for GitHub user accounts are present.
  authorized_key:
    user: "{{ item.username | default(item) }}"
    key: "{{ github_url }}/{{ item.username | default(item) }}.keys"
    manage_dir: true
    exclusive: "{{ github_users_authorized_keys_exclusive }}"
  with_items: "{{ users }}"

# TODO use vault to get more informations about user (email)
- name: Fetch user info from github api
  uri:
    #user: "{{ jenkins.user }}"
    #password: "{{ jenkins.password }}"
    method: GET
    #force_basic_auth: yes
    url: "{{ github_api }}" # "{{ github_user_token }}"
    return_content: yes
  register: user_info_object

- name: look user infos
  debug:
    msg: "{{ user_info_object }}"