---

# TODO use vault to get more informations about user (email)
- name: Fetch main user info from github api
  uri:
    #username: "{{ user_item.username }}"
    method: GET
    headers:
      token: "{{ user_item.github_user_token }}"
      Accept: 'application/json'
    #force_basic_auth: yes
    url: "{{ github_api }}/{{ user_item.username }}" # "{{ github_user_token }}"
    return_content: yes
  register: user_info_object
  when: user_item.github_user_token is defined

- name: look user infos
  debug:
    msg: "{{ user_info_object }}"

- name: apply git config to each user
  template:
    src: "{{ item.src }}"
    dest: "{{ user_item.home }}/{{ item.dest }}"
    owner: "{{ user_item.username }}"
    mode: '0600'
  with_items:
      - { src: gitignore_global , dest: ".gitignore_global" }
      - { src: gitconfig, dest: ".gitconfig" }

- name: Include zsh config
