---

# get user on github
- name: Ensure authorized_keys for GitHub user accounts are present.
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ github_url }}/{{ item.username }}.keys"
    manage_dir: true
    exclusive: "{{ item.authorized_keys_exclusive | default(users_authorized_keys_exclusive) }}"
  with_items: "{{ users }}"

# TODO use vault to get more informations about user (email)
- name: Fetch main user info from github api
  uri:
    username: "{{ item.username }}"
    method: GET
    #force_basic_auth: yes
    url: "{{ github_api }}" # "{{ github_user_token }}"
    return_content: yes
  register: user_info_object
  with_items: "{{ users }}"
  when: users is defined

- name: look user infos
  debug:
    msg: "{{ user_info_object }}"
