---
- name: restart timesyncd
  systemd:
    state: restarted
    name: systemd-timesyncd

# compliant with security role
- name: restart sshd
  service:
    name: "{{ security_sshd_name|d('sshd') }}"
    state: "{{ security_ssh_restart_handler_state|d('restarted') }}"
